### ISSUE TITLE
check-cluster.rb don't work for password protected redis

### ISSUE THREAD

**Issue by adriananeci** [Yelp/puppet-monitoring_check#153]
Hi team,

After adding password to our redis instance, check-cluster.rb stopped working.
After a short look I've noticed that tiny_redis class don't have any option to provide the redis password.
The command used is 
`/etc/sensu/plugins/check-cluster.rb  --cluster-name prod --check check_backup`

And the output:

`CheckCluster CRITICAL: Redis error: NOAUTH Authentication required. (RuntimeError): ["/etc/sensu/plugins/tiny_redis.rb:91:in `parse_response'", "/etc/sensu/plugins/tiny_redis.rb:84:in `method_missing'", "/etc/sensu/plugins/tiny_redis.rb:27:in `block in check_redis_connection'", "/etc/sensu/plugins/tiny_redis.rb:26:in `upto'", "/etc/sensu/plugins/tiny_redis.rb:26:in `check_redis_connection'", "/etc/sensu/plugins/tiny_redis.rb:17:in `initialize'", "/etc/sensu/plugins/check-cluster.rb:101:in `new'", "/etc/sensu/plugins/check-cluster.rb:101:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.0.1/lib/sensu-plugin/cli.rb:58:in `block in '"]`

Is there any way to provide the redis password to the current module?

Regards,
Adrian/

**Comment by keymone** [comment]
yeah, currently authenticating is not supported, but shouldn't be hard to add:

replacing https://github.com/Yelp/puppet-monitoring_check/blob/master/files/check-cluster.rb#L236 with something like:

    TinyRedis::Client.
      new(redis_config[:host], redis_config[:port]).
      tap { |tr| tr.auth(redis_config[:password]) }

should do it.

PRs are welcome :)

**Comment by keymone** [comment]
@adriananeci hard to say without seeing the diff you're working with, but i would guess you're calling `.tap` on `redis_config[:port]` rather than an instance of `TinyRedis::Client`.

`TinyRedis::Client` should have no problem running the AUTH command because commands are dispatched via `method_missing`, which is ruby's way to say "if a method is not defined - run me instead". see line 15 in the gist you've linked.

here is the more imperative way to write the above change:

    @redis = begin
      tr = TinyRedis::Client.new(redis_config[:host], redis_config[:port])
      tr.auth(redis_config[:password])
      tr # return actual client object from this block
    end

**Comment by adriananeci** [comment]
Ah, yeah, sorry, my bad.
You were right, I've omitted a bracket :D 
I can confirm that it's working now.

Thanks.
